Update react.js.yml

diff --git a/.github/workflows/react.js.yml b/.github/workflows/react.js.yml
--- a/.github/workflows/react.js.yml
+++ b/.github/workflows/react.js.yml
@@ -42,10 +42,10 @@ jobs:
   
     - name: 🚀 Deploy to S3
       run: |
-          if [ -z "${{ secrets.S3_BUCKET }}" ]; then
-          echo "Error: S3_BUCKET secret is not set."
-          exit 1
-        fi
+        if [ -z "${{ secrets.S3_BUCKET }}" ]; then
+        echo "Error: S3_BUCKET secret is not set."
+        exit 1
+      fi
           aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }} --exact-timestamps --delete --region ${{ secrets.AWS_REGION }}
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
