Update react.js.yml

diff --git a/.github/workflows/react.js.yml b/.github/workflows/react.js.yml
--- a/.github/workflows/react.js.yml
+++ b/.github/workflows/react.js.yml
@@ -53,17 +53,17 @@ jobs:
 #        AWS_REGION: ${{ secrets.AWS_REGION }}
 #        S3_BUCKET: ${{ secrets.S3_BUCKET }}
 #
-#    - name: 🔄 Invalidate CloudFront Cache
-#      run: |
-#        if [ -z "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
-#          echo "Error: CLOUDFRONT_DISTRIBUTION_ID secret is not set."
-#          exit 1
-#        fi
-#        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
-#      env:
-#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#
+    - name: 🔄 Invalidate CloudFront Cache
+      run: |
+        if [ -z "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
+          echo "Error: CLOUDFRONT_DISTRIBUTION_ID secret is not set."
+          exit 1
+        fi
+        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
     # Debug Step to Print Environment Variables
     - name: 🐛 Debug Environment Variables
       run: |
